/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AnimatedContainer {
    'duration': number;
    'easing': string;
    'stagger': number;
  }
}

declare global {


  interface HTMLAnimatedContainerElement extends Components.AnimatedContainer, HTMLStencilElement {}
  var HTMLAnimatedContainerElement: {
    prototype: HTMLAnimatedContainerElement;
    new (): HTMLAnimatedContainerElement;
  };
  interface HTMLElementTagNameMap {
    'animated-container': HTMLAnimatedContainerElement;
  }
}

declare namespace LocalJSX {
  interface AnimatedContainer extends JSXBase.HTMLAttributes<HTMLAnimatedContainerElement> {
    'duration'?: number;
    'easing'?: string;
    'stagger'?: number;
  }

  interface IntrinsicElements {
    'animated-container': AnimatedContainer;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


